---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/operator.victoriametrics.com/vmservicescrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vector-syslog
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vector
      app.kubernetes.io/instance: vector-syslog
  jobLabel: app.kubernetes.io/instance
  endpoints:
    - port: prom-exporter
      path: /metrics
      interval: 30s
