---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/snapshot.storage.k8s.io/volumesnapshotclass_v1.json
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: truenas-snapshot
driver: org.truenas.csi
deletionPolicy: Delete
