---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: freshrss
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: freshrss-secret
    template:
      data:
        OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        OIDC_CLIENT_CRYPTO_KEY: "{{ .OIDC_CLIENT_CRYPTO_KEY }}"
  dataFrom:
    - extract:
        key: freshrss
