---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vmsingle-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: vmsingle-oidc-secret
    template:
      data:
        client-secret: "{{ .OIDC_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: victoria-metrics
---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vmalertmanager-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: vmalertmanager-oidc-secret
    template:
      data:
        client-secret: "{{ .OIDC_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: alertmanager
