---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./externalsecret.yaml
  - ./vmstaticscrape.yaml
  - ./vmservicescrape-stack.yaml
  - ./vmrule-stack.yaml
  - ./vmrule-infrastructure.yaml
  - ./httproute.yaml
  - ./grafanadashboards.yaml
