---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qbittorrent-secret
    creationPolicy: Owner
  data:
    # - secretKey: WIREGUARD_ENDPOINT_IP
    #   remoteRef:
    #     key: protonvpn
    #     property: QBITTORRENT_VPN_ENDPOINT_IP
    # - secretKey: WIREGUARD_PUBLIC_KEY
    #   remoteRef:
    #     key: protonvpn
    #     property: QBITTORRENT_WIREGUARD_PUBLIC_KEY
    # - secretKey: WIREGUARD_PRIVATE_KEY
    #   remoteRef:
    #     key: protonvpn
    #     property: QBITTORRENT_WIREGUARD_PRIVATE_KEY
    # - secretKey: WIREGUARD_ADDRESSES
    #   remoteRef:
    #     key: protonvpn
    #     property: QBITTORRENT_WIREGUARD_ADDRESSES
    # - secretKey: WIREGUARD_PRESHARED_KEY
    #   remoteRef:
    #     key: protonvpn
    #     property: WIREGUARD_PRESHARED_KEY
    # - secretKey: WIREGUARD_ENDPOINT_PORT
    #   remoteRef:
    #     key: protonvpn
    #     property: WIREGUARD_ENDPOINT_PORT
    - secretKey: xseed_api_key
      remoteRef:
        key: cross-seed
        property: CROSS_SEED_API_KEY
    - secretKey: GLUETUN_CONTROL_SERVER_API_KEY
      remoteRef:
        key: gluetun
        property: GLUETUN_API_KEY
    - secretKey: FIREWALL_VPN_INPUT_PORTS
      remoteRef:
        key: protonvpn
        property: FIREWALL_VPN_INPUT_PORTS
    - secretKey: FIREWALL_INPUT_PORTS
      remoteRef:
        key: protonvpn
        property: FIREWALL_INPUT_PORTS
    - secretKey: VPN_SERVICE_PROVIDER
      remoteRef:
        key: protonvpn
        property: VPN_SERVICE_PROVIDER
    - secretKey: HEALTH_TARGET_ADDRESS
      remoteRef:
        key: protonvpn
        property: HEALTH_TARGET_ADDRESS
    - secretKey: PUBLICIP_API
      remoteRef:
        key: protonvpn
        property: PUBLICIP_API
    - secretKey: PUBLICIP_API_TOKEN
      remoteRef:
        key: protonvpn
        property: PUBLICIP_API_TOKEN
    - secretKey: WIREGUARD_ENDPOINT_IP
      remoteRef:
        key: protonvpn
        property: WIREGUARD_ENDPOINT_IP
    - secretKey: WIREGUARD_PUBLIC_KEY
      remoteRef:
        key: protonvpn
        property: WIREGUARD_PUBLIC_KEY
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: protonvpn
        property: WIREGUARD_PRIVATE_KEY
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: protonvpn
        property: WIREGUARD_ADDRESSES
    - secretKey: WIREGUARD_PRESHARED_KEY
      remoteRef:
        key: protonvpn
        property: WIREGUARD_PRESHARED_KEY
    - secretKey: WIREGUARD_ENDPOINT_PORT
      remoteRef:
        key: protonvpn
        property: WIREGUARD_ENDPOINT_PORT
---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-gluetun
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qbittorrent-gluetun
    creationPolicy: Owner
    template:
      data:
        auth.toml: |
          [[roles]]
          name = "gluetun-qb-port-sync"
          routes = [
            "GET /v1/publicip/ip",
            "GET /v1/vpn/portforwarded",
            "GET /v1/vpn/status"
          ]
          auth = "apikey"
          apikey = "{{ .GLUETUN_API_KEY }}"
  dataFrom:
    - extract:
        key: gluetun
