---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app powerdns
spec:
  chartRef:
    kind: OCIRepository
    name: powerdns
  interval: 1h
  values:
    fullnameOverride: external-dns-powerdns
    provider:
      name: rfc2136
    env:
      - name: EXTERNAL_DNS_RFC2136_HOST
        value: "192.168.123.250"
      - name: EXTERNAL_DNS_RFC2136_PORT
        value: "5300"
      - name: EXTERNAL_DNS_RFC2136_ZONE
        value: "${SECRET_DOMAIN}"
      - name: EXTERNAL_DNS_RFC2136_TSIG_KEYNAME
        value: "external-dns"
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET_ALG
        value: "hmac-sha512"
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
        valueFrom:
          secretKeyRef:
            name: &secret powerdns-secret
            key: EXTERNAL_DNS_RFC2136_TSIG_SECRET
    triggerLoopOnEvent: true
    policy: sync
    sources:
      - gateway-httproute
      - service
    txtOwnerId: technitium
    txtPrefix: "k8s."
    domainFilters:
      - ${SECRET_DOMAIN}
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 1Gi
