---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netdata
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: netdata-secret
    template:
      data:
        NETDATA_CLAIM_TOKEN: "{{ .NETDATA_CLAIM_TOKEN }}"
        NETDATA_CLAIM_ROOMS: "{{ .NETDATA_CLAIM_ROOMS }}"
  dataFrom:
    - extract:
        key: netdata
