---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-postgres-s3
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: netbox-postgres-s3-secret
    template:
      data:
        ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        ACCESS_SECRET_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: cnpg-s3-backup
---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-postgres-superuser
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: netbox-postgres-superuser-secret
    template:
      engineVersion: v2
      data:
        username: postgres
        password: "{{ .POSTGRES_PASSWORD }}"
  dataFrom:
    - extract:
        key: netbox-postgres
