---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: autobrr
spec:
  components:
    - ../../../../components/nfs-scaler
    - ../../../../components/volsync-direct
  dependsOn:
    - name: truenas-csi
      namespace: truenas-csi
  interval: 1h
  path: ./kubernetes/apps/downloads/autobrr/app
  postBuild:
    substitute:
      APP: autobrr
      VOLSYNC_CAPACITY: 50Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: downloads
  wait: false
