---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kgateway-gateway-api-crds
spec:
  interval: 12h
  path: ./kubernetes/apps/network/kgateway/gateway-api-crds
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: gateways.gateway.networking.k8s.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: httproutes.gateway.networking.k8s.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: gatewayclasses.gateway.networking.k8s.io
---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kgateway
spec:
  dependsOn:
    - name: kgateway-gateway-api-crds
  interval: 1h
  path: ./kubernetes/apps/network/kgateway/control-plane
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kgateway-system
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kgateway-config
spec:
  dependsOn:
    - name: kgateway
    - name: certificates-import
      namespace: network
  interval: 1h
  path: ./kubernetes/apps/network/kgateway/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
  wait: false
