---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmrule_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: sonarr-logs
  namespace: observability
  labels:
    rule-type: vlogs
spec:
  groups:
    - name: sonarr-logs
      type: vlogs
      interval: 1m
      rules:
        - alert: SonarrDatabaseIsLocked
          expr: |
            {app="sonarr"} | regexp "(?i)database is locked" | stats count() errors | filter errors:>0
          for: 5m
          annotations:
            summary: Sonarr is experiencing database lock issues
            description: "Sonarr has encountered database lock errors in the last 5 minutes"
          labels:
            severity: critical
            app: sonarr

        - alert: SonarrDatabaseIsMalformed
          expr: |
            {app="sonarr"} | regexp "(?i)database disk image is malformed" | stats count() errors | filter errors:>0
          for: 5m
          annotations:
            summary: Sonarr database is corrupted
            description: "Sonarr has encountered database corruption errors in the last 5 minutes"
          labels:
            severity: critical
            app: sonarr
