---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth

components:
  - ../../components/alerts
  - ../../components/cluster-secret

resources:
  - ./namespace.yaml
  - ./pocket-id/ks.yaml
