---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: scale-csi
spec:
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
    - name: snapshot-controller
      namespace: kube-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: scale-csi
      namespace: scale-csi
  interval: 1h
  path: ./kubernetes/apps/scale-csi/scale-csi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: scale-csi
  wait: true
