---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kgateway
spec:
  controllerName: kgateway.dev/kgateway
  parametersRef:
    group: gateway.kgateway.dev
    kind: GatewayParameters
    name: kgateway-proxy-params
    namespace: network
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kgateway-external
  annotations:
    external-dns.alpha.kubernetes.io/target: &externalHostname "kgateway-external.${SECRET_DOMAIN}"
    gatus.home-operations.com/endpoint: |-
      client:
        dns-resolver: tcp://192.168.123.250:53
      group: external
spec:
  gatewayClassName: kgateway
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: *externalHostname
      lbipam.cilium.io/ips: 192.168.255.12
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: home-ops-wc-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kgateway-internal
  annotations:
    external-dns.alpha.kubernetes.io/target: &internalHostname "kgateway-internal.${SECRET_DOMAIN}"
    gatus.home-operations.com/endpoint: |-
      group: internal
spec:
  gatewayClassName: kgateway
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: *internalHostname
      lbipam.cilium.io/ips: 192.168.255.11
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: home-ops-wc-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-redirect
  annotations:
    external-dns.alpha.kubernetes.io/controller: none
spec:
  parentRefs:
    - name: kgateway-external
      namespace: network
      sectionName: http
    - name: kgateway-internal
      namespace: network
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
