---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kgateway-proxy
spec:
  jobLabel: kgateway-proxy
  namespaceSelector:
    matchNames:
      - network
  selector:
    matchLabels:
      kgateway: kube-gateway
  podMetricsEndpoints:
    - port: http-monitoring
      path: /stats/prometheus
      honorLabels: true
---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kgateway
  namespace: kgateway-system
spec:
  jobLabel: kgateway
  namespaceSelector:
    matchNames:
      - kgateway-system
  selector:
    matchLabels:
      app.kubernetes.io/name: kgateway
  endpoints:
    - port: metrics
      path: /metrics
      honorLabels: true
