---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: karakeep
spec:
  components:
    - ../../../../components/volsync-direct
  dependsOn:
    - name: truenas-csi
      namespace: truenas-csi
  interval: 1h
  path: ./kubernetes/apps/self-hosted/karakeep/app
  postBuild:
    substitute:
      APP: karakeep
      VOLSYNC_CAPACITY: 5Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: self-hosted
  wait: false
