---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name actions-runner-controller
spec:
  chartRef:
    kind: OCIRepository
    name: actions-runner-controller
  interval: 1h
  values:
    fullnameOverride: *name
    resources:
      requests:
        cpu: 100m
        memory: 19Mi
      limits:
        memory: 64Mi
