---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cross-seed
spec:
  components:
    - ../../../../components/nfs-scaler
    - ../../../../components/volsync-direct
  dependsOn:
    - name: truenas-csi
      namespace: truenas-csi
    - name: keda
      namespace: observability
    - name: qui
      namespace: downloads
  interval: 1h
  path: ./kubernetes/apps/downloads/cross-seed/app
  postBuild:
    substitute:
      APP: cross-seed
      VOLSYNC_CAPACITY: 5Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: downloads
  wait: false
