---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: scale-csi
spec:
  chartRef:
    kind: OCIRepository
    name: scale-csi
  interval: 1h
  values:
    csiDriverName: org.scale.csi

    image:
      repository: ghcr.io/gizmotickler/scale-csi
      tag: v1.0.0
      pullPolicy: IfNotPresent

    truenas:
      host: nas01.${SECRET_DOMAIN}
      port: 443
      secure: true
      skipTLSVerify: true
      existingSecret: scale-csi-secret

    zfs:
      parentDataset: flashstor/scale-csi

    nfs:
      enabled: true
      server: nas01.${SECRET_DOMAIN}

    iscsi:
      enabled: true
      portal: 192.168.120.10
      portalPort: 3260
      portalGroupId: 2
      initiatorGroupId: 1

    storageClass:
      create: false

    controller:
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 2000m
          memory: 2048Mi

    node:
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 4000m
          memory: 2048Mi
