---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/storage.k8s.io/storageclass_v1.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: scale-iscsi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: org.scale.csi
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  protocol: iscsi
  fsType: ext4
