---
originRequest:
  originServerName: "external.${SECRET_DOMAIN}"
  keepAliveTimeout: 3600s
  tcpKeepAlive: 7200s

ingress:
  - hostname: "${SECRET_DOMAIN}"
    service: &svc https://envoy-external.network.svc.cluster.local
  - hostname: "*.${SECRET_DOMAIN}"
    service: *svc
  - service: http_status:404
