---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/v1/configmap.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: zot-config
data:
  config.json: |
    {
      "distSpecVersion": "1.1.1",
      "storage": {
        "rootDirectory": "/var/lib/registry",
        "dedupe": true,
        "gc": true,
        "gcDelay": "24h",
        "gcInterval": "6h"
      },
      "http": {
        "address": "0.0.0.0",
        "port": "5000"
      },
      "log": {
        "level": "info"
      },
      "extensions": {
        "sync": {
          "enable": true,
          "registries": [
            {
              "urls": ["https://ghcr.io"],
              "onDemand": true,
              "tlsVerify": true,
              "maxRetries": 5,
              "retryDelay": "30s",
              "content": [
                {
                  "prefix": "/controlplaneio-fluxcd/**"
                },
                {
                  "prefix": "/fluxcd/**"
                },
                {
                  "prefix": "/bjw-s-labs/**"
                },
                {
                  "prefix": "/home-operations/**"
                },
                {
                  "prefix": "/victoriametrics/**"
                },
                {
                  "prefix": "/rook/**"
                },
                {
                  "prefix": "/prometheus-community/**"
                },
                {
                  "prefix": "/stakater/**"
                },
                {
                  "prefix": "/spegel-org/**"
                },
                {
                  "prefix": "/piraeusdatastore/**"
                },
                {
                  "prefix": "/openebs/**"
                },
                {
                  "prefix": "/netbox-community/**"
                },
                {
                  "prefix": "/actions/**"
                },
                {
                  "prefix": "/grafana/**"
                },
                {
                  "prefix": "/project-zot/**"
                }
              ]
            }
          ]
        }
      }
    }
