---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/storage.k8s.io/storageclass_v1.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: scale-nfs
provisioner: org.scale.csi
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  protocol: nfs
mountOptions:
  - nfsvers=4
  - noatime
