---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pihole-dns
spec:
  interval: 1h
  path: ./kubernetes/apps/network/pihole-dns/app
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-config-secret
        optional: false
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
  wait: false
